name: "SPIDYNAL SYSTEM"
description: "Your Private System Analyst & Diagnostics Tool."
author: "maiz-an"

inputs:
  command:
    description: "Command to pass to SPIDYNAL.exe (e.g., 'net speed', 'spidy lens')"
    required: true
    default: "net speed"
  query:
    description: "Query for spidy lens (e.g., file name)"
    required: false
  extension:
    description: "File extension for spidy lens (e.g., '.txt')"
    required: false

runs:
  using: "composite"
  steps:
    - name: Run SPIDYNAL.exe
      shell: cmd
      run: |
        echo Running SPIDYNAL SYSTEM...
        if not "%~2"=="" (
          set QUERY=%~2
        ) else (
          set QUERY=""
        )
        if not "%~3"=="" (
          set EXTENSION=%~3
        ) else (
          set EXTENSION=""
        )
        SPIDYNAL.exe "${{ inputs.command }}" "%QUERY%" "%EXTENSION%"

branding:
  icon: "terminal"
  color: "red"
